# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "The Ampersand CLI"
  homepage ""
  version "1.0.6"

  on_macos do
    on_intel do
      url "https://github.com/amp-labs/cli/releases/download/v1.0.6/cli_Darwin_x86_64.tar.gz"
      sha256 "0373b1ba89604ee216e0b340d08b546cfbd17d327de0d9dc989e6923190629c9"

      def install
        bin.install "amp"
      end
    end
    on_arm do
      url "https://github.com/amp-labs/cli/releases/download/v1.0.6/cli_Darwin_arm64.tar.gz"
      sha256 "8fcdd800a6004b60205dea2612d8cc2bca19a80bff2bb77ecc002a18bfd9b6ab"

      def install
        bin.install "amp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amp-labs/cli/releases/download/v1.0.6/cli_Linux_x86_64.tar.gz"
        sha256 "a3e64cb14045cb7d5ba981a2cb5a2fd88754996d2db05ec313b0c8442a9e4280"

        def install
          bin.install "amp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amp-labs/cli/releases/download/v1.0.6/cli_Linux_arm64.tar.gz"
        sha256 "19be5869e537c290da75db3604ace596b57dc60fcca87555971453ca8da288cf"

        def install
          bin.install "amp"
        end
      end
    end
  end
end
