# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "The Ampersand CLI"
  homepage ""
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/amp-labs/cli/releases/download/v1.0.0/cli_Darwin_x86_64.tar.gz"
      sha256 "a6a3e23ed1cda5e0f90f9d19f64b074d7b7ce3220e46f1822f67187efed18866"

      def install
        bin.install "amp"
      end
    end
    on_arm do
      url "https://github.com/amp-labs/cli/releases/download/v1.0.0/cli_Darwin_arm64.tar.gz"
      sha256 "c8957ea8a09219dba6096a79fdb66972ebc2836aadeff5d3ef743d881446bf15"

      def install
        bin.install "amp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amp-labs/cli/releases/download/v1.0.0/cli_Linux_x86_64.tar.gz"
        sha256 "b5875c9725a934278f2f1b91e159e17b22f9b0959a658883e43ea92e114238b0"

        def install
          bin.install "amp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amp-labs/cli/releases/download/v1.0.0/cli_Linux_arm64.tar.gz"
        sha256 "fcd96db3bcbb583c7a3bd27b542346a2f460fce2edd62b6f2eb49026e804d095"

        def install
          bin.install "amp"
        end
      end
    end
  end
end
